# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
# Path to your oh-my-zsh installation.
export ZSH=/home/hobochild/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
##################################################
# Settings
##################################################

# vim mode

export EDITOR=vim

plugins=(
  git
  history-substring-search
  zsh-completions
)

autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

### BASIS DEV ###
export BASIS_DEPLOY=~/Play/basis-deploy
export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

##################################################
# Aliases
##################################################

alias reload="source $HOME/.zshrc"
alias ll="ls -l"
alias tele="telepresence"
alias venv="virtualenv venv"
alias activate="source venv/bin/activate"
alias sesh="tmux new-session -s"
alias kop='function _kill_on_port(){ fuser -k $1/tcp };_kill_on_port'
alias xclip='xclip -sel clip'
alias pom="sleep 2500 && zenity --warning --text='25 minutes passed'"

# added by travis gem
[ -f /home/hobochild/.travis/travis.sh ] && source /home/hobochild/.travis/travis.sh

# Make sure yarn's global dir findable
export PATH="$(yarn global bin):$PATH"
# Make sure pipenv global dir is findable
export PATH="${HOME}/.local/bin:$PATH"
export PATH=$PATH:/usr/local/go/bin
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/bin/google-cloud-sdk/bin:$PATH"
export GOPATH="${HOME}/Code/go"
export PATH="${GOPATH}/bin:$PATH"

bindkey -v
# Make the escape mode the same as in vim.
bindkey jk vi-cmd-mode

##################################################
# Gratitude - https://github.com/hobochild/gratitude
##################################################

# gratitude

##################################################
# Auto compeletions
##################################################
source <(kubectl completion zsh)

## android studio
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/usr/local/bin/google-cloud-sdk/path.zsh.inc' ]; then . '/usr/local/bin/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/usr/local/bin/google-cloud-sdk/completion.zsh.inc' ]; then . '/usr/local/bin/google-cloud-sdk/completion.zsh.inc'; fi

vi-append-x-selection () { RBUFFER=$(xclip -o </dev/null)$RBUFFER; }
zle -N vi-append-x-selection
bindkey -a '^X' vi-append-x-selection
vi-yank-x-selection () { print -rn -- $CUTBUFFER | xclip -sel clip; }
zle -N vi-yank-x-selection
bindkey -a '^Y' vi-yank-x-selection

