live_config_reload = true

import = [
"~/.config/alacritty/catppuccin-frappe.toml",
]

[font]
normal.family = "JetBrainsMonoNF-Bold"
bold.family = "JetBrainsMonoNF-ExtraBold"
italic.family = "JetBrainsMonoNF-BoldItalic"
bold.italic.family = "JetBrainsMonoNF-ExtraBoldItalic"
